In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

In [20]:
df = pd.read_csv("Salary_Data.csv")

In [21]:
df.head()

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0

In [22]:
df.isnull().sum()

Age                    2
Gender                 2
Education Level        2
Job Title              2
Years of Experience    2
Salary                 2
dtype: int64

In [23]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
370     True
371    False
372     True
373     True
374     True
Length: 375, dtype: bool

In [24]:
df = df.dropna()

In [25]:
df.isnull().sum()

Age                    0
Gender                 0
Education Level        0
Job Title              0
Years of Experience    0
Salary                 0
dtype: int64

In [26]:
df.info()

<class 'pandas.DataFrame'>
Index: 373 entries, 0 to 374
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  373 non-null    float64
 1   Gender               373 non-null    str
 2   Education Level      373 non-null    str
 3   Job Title            373 non-null    str
 4   Years of Experience  373 non-null    float64
 5   Salary               373 non-null    float64
dtypes: float64(3), str(3)
memory usage: 20.4 KB

In [27]:
df.describe()

              Age  Years of Experience         Salary
count  373.000000           373.000000     373.000000
mean    37.431635            10.030831  100577.345845
std      7.069073             6.557007   48240.013482
min     23.000000             0.000000     350.000000
25%     31.000000             4.000000   55000.000000
50%     36.000000             9.000000   95000.000000
75%     44.000000            15.000000  140000.000000
max     53.000000            25.000000  250000.000000

In [28]:
df = df.drop_duplicates()

In [29]:
df.shape

(324, 6)

In [16]:
df.duplicated().sum()

np.int64(0)

In [31]:
df.columns

Index(['Age', 'Gender', 'Education Level', 'Job Title', 'Years of Experience',
       'Salary'],
      dtype='str')

In [ ]:
df = pd.get_dummies(df)

In [36]:
X = df.drop("Salary", axis=1)
y = df["Salary"]

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [38]:
print(X_test)
print(y_test)
print(X_train)
print(y_train)

      Age  Gender Education Level                   Job Title  \
132  40.0  Female        Master's  Senior Training Specialist
108  41.0  Female        Master's    Senior Marketing Analyst
137  30.0  Female      Bachelor's    Junior Marketing Manager
9    38.0    Male             PhD            Senior Scientist
181  37.0    Male        Master's     Senior Business Analyst
..    ...     ...             ...                         ...
104  39.0  Female        Master's  Senior Project Coordinator
233  35.0    Male      Bachelor's   Senior Operations Analyst
60   51.0  Female        Master's      Director of Operations
94   33.0    Male      Bachelor's            Business Analyst
278  36.0    Male      Bachelor's      Senior Product Manager

     Years of Experience
132                 12.0
108                 14.0
137                  4.0
9                   10.0
181                  9.0
..                   ...
104                 13.0
233                  8.0
60                  23.0
94                   7.0
278                  8.0

[65 rows x 5 columns]
132    100000.0
108    100000.0
137     50000.0
9      110000.0
181    105000.0
         ...
104     80000.0
233     85000.0
60     170000.0
94      75000.0
278     95000.0
Name: Salary, Length: 65, dtype: float64
      Age  Gender Education Level                     Job Title  \
73   28.0    Male      Bachelor's  Technical Support Specialist
182  44.0  Female             PhD            Senior UX Designer
17   39.0    Male             PhD               Senior Engineer
24   41.0    Male        Master's             Financial Manager
146  42.0  Female             PhD         Senior Data Scientist
..    ...     ...             ...                           ...
189  28.0    Male      Bachelor's     Junior Operations Analyst
71   39.0  Female      Bachelor's                     Recruiter
106  30.0  Female      Bachelor's      Digital Content Producer
284  35.0    Male      Bachelor's      Senior Financial Manager
102  49.0  Female        Master's             Senior HR Manager

     Years of Experience
73                   2.0
182                 15.0
17                  12.0
24                  13.0
146                 16.0
..                   ...
189                  1.5
71                  11.0
106                  3.0
284                  9.0
102                 19.0

[259 rows x 5 columns]
73      40000.0
182    145000.0
17     115000.0
24     140000.0
146    150000.0
         ...
189     35000.0
71      70000.0
106     50000.0
284    100000.0
102    150000.0
Name: Salary, Length: 259, dtype: float64

In [43]:
df.describe()

              Age  Years of Experience         Salary
count  324.000000           324.000000     324.000000
mean    37.382716            10.058642   99985.648148
std      7.185844             6.650470   48652.271440
min     23.000000             0.000000     350.000000
25%     31.000000             4.000000   55000.000000
50%     36.500000             9.000000   95000.000000
75%     44.000000            16.000000  140000.000000
max     53.000000            25.000000  250000.000000

In [44]:
model = LinearRegression()
model.fit(X_train, y_train)

ValueError: could not convert string to float: 'Male'